### ISSUE TITLE
using CMF broken

### ISSUE THREAD

**Issue by tgfisher** [degleris1/CMF.jl#34]
after doing a pkg add, using CMF has a load error "ANLS not defined"...

pretty sure this is because include("./anls.jl") is commented out in the CMF module.

**Comment by degleris1** [comment]
Fixed, thanks to @bantin. Thanks!

**Comment by degleris1** [comment]
EDIT: A double import bug may now cause a crash. This has been revised in the latest branch `anthony`, which is waiting to be merged to master.

**Comment by bantin** [comment]
@tgfisher We're working on getting this fixed. I think none of are super experienced with Julia's import mechanisms so we're figuring it out as we go. Should be ready to go by end of the day.

**Comment by bantin** [comment]
@tgfisher This should be fixed now. If can confirm that `using CMF` is working for you, I'll close this.

**Comment by tgfisher** [comment]
Works for me. Thanks guys.
