### ISSUE TITLE
plot_Ws broken: eachrow not defined

### ISSUE THREAD

**Issue by bantin** [degleris1/CMF.jl#39]
@ahwillia
 I'm having an issue using the `sortperm(r::CNMF_results)` because `eachrow` is undefined. My best guess is that you're using Julia 1.1 and that it's a difference between 1.0 and 1.1. 

Do we want to change this bit of code to be compatible with 1.0 or do we want to require 1.1 and above?

**Comment by ahwillia** [comment]
No strong feelings on my part.

**Comment by bantin** [comment]
Ok, resolved in #41
